version: 0.2

phases:
  build:
    commands:
      - pip install -r requirements.txt  # If you have external dependencies, include them in requirements.txt
      - zip -r lambda-package.zip *
      - aws lambda update-function-code --function-name YourLambdaFunctionName --zip-file fileb://lambda-package.zip
      - aws lambda invoke --function-name YourLambdaFunctionName
artifacts:
  files: lambda-package.zip
